
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcwttkekflxffjzcqovi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjd3R0a2VrZmx4ZmZqemNxb3ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTkwMzcsImV4cCI6MjA2MDY5NTAzN30.u9gLEu5eEOBYp8u8LLUjdZxqqFQ15GuxkrGRvxm38GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
